# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-09-08 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('pic_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trunk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.CharField(blank=True, max_length=50, null=True)),
                ('engine', models.CharField(blank=True, max_length=50, null=True)),
                ('gear_box', models.CharField(blank=True, max_length=50, null=True)),
                ('carr_length', models.CharField(blank=True, max_length=50, null=True)),
                ('tf_drive', models.CharField(blank=True, max_length=50, null=True)),
                ('carr_st', models.CharField(blank=True, max_length=50, null=True)),
                ('emiss_standard', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
